### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dshame** [webcpp/mongols#12]
src/openssl.cpp: In constructor ‘mongols::openssl::openssl(const string&, const string&, mongols::openssl::version_t, const string&, long int)’:
src/openssl.cpp:30:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
src/openssl.cpp:30:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
src/openssl.cpp:33:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
src/openssl.cpp:33:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
src/openssl.cpp:39:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
src/openssl.cpp:39:55: error: ‘const SSL_METHOD* TLSv1_2_server_method()’ is deprecated [-Werror=deprecated-declarations]
         this->ctx = SSL_CTX_new(TLSv1_2_server_method());
                                                       ^
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/bio.h:13,
                 from inc/mongols/openssl.hpp:10,
                 from src/openssl.cpp:2:
/usr/include/openssl/ssl.h:1890:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
 ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:85：src/openssl.o] 错误 1
make: *** 正在等待未完成的任务....

**Comment by webcpp** [comment]
add `-Wno-deprecated-declarations` to Makefile or git pull

**Comment by dshame** [comment]
谢谢
