### ISSUE TITLE
tcpserver的一些疑惑

### ISSUE THREAD

**Issue by lrh450330** [webcpp/mongols#19]
1、支持在多进程化的同时多线程化，目前看来只有单线程吧
2、非进程化也是单线程处理，thread_size直接置0，也没有接口设置
3、epoll的监听事件数组默认64大小，这个是最优配置么
4、epoll使用了ET模式，读了下work代码，读数据的时候是否需要考虑当 recv() 返回的大小如果等于请求的大小，那么很有可能缓冲区还有数据未读完，也意味着该次事件还没有处理完，所以还需要再次读取？
5、假如发送端流量大于接收端的流量 ( 意思是 epoll 所在的程序读比转发的 socket 要快 ), 由于是非阻塞的socket, 那么 send() 函数虽然返回 , 但实际缓冲区的数据并未真正发给接收端，这样不断的读和发，当缓冲区满后会产生 EAGAIN 错误，这种情况是否也应该考量一下
6、send_to_other_filter函数看起来没有什么意义啊

这些是基于什么考虑呢，非进程化跑example里的benchmark性能根本起不来啊

**Comment by webcpp** [comment]
1.mongols在version-1.3.4之后,对多线程机制的使用做了调整，仅当需要将消息在各个连接之间转发时，才把相关任务作为后台任务由线程池执行。也就是说，除了ws_server，其他服务器在构造时，都应该将设置线程数的第五个参数设置为0。请阅读https://mongols.hi-nginx.com/doc/others.html。

2.max_event_size默认大小为64，构造时可自行增减。

3.send_to_other_filter在ws_server有特定用途。以备不虞。

example中的tcp_server设置了`send_to_other = true`。echo压测时务必改为`send_to_other = false`。并且，请把loop或client设置较大值，默认值太小了，跑太快，跟没跑一样。比如:`./tcp_server_benchmark --loop=100000 --client=50000`。
