### ISSUE TITLE
tcp惊群处理

### ISSUE THREAD

**Issue by lrh450330** [webcpp/mongols#21]
多进程场景下，fork之后创建epollfd：
1. 主进程创建listendfd
2. 主进程创建多个子进程
3. 每个子进程创建自已的epollfd
4. 每个子进程把listenfd加入到epollfd中
5. 当一个连接进来时，会触发epoll惊群，多个子进程epoll同时会触发
每个子进程的epoll是不同的epoll, 虽然listenfd是同一个，但新连接过来时, accept会触发惊群，但内核不知道该发给哪个监听进程，因为不是同一个epoll。多进程那部分代码的共享内存锁，是不是预期做这个事情的，但最终也没有用上？

**Comment by webcpp** [comment]
较新内核能自行处理该问题。
