### ISSUE TITLE
I' m looking forward to hear your response. thanks.

### ISSUE THREAD

**Issue by yaoguangluo** [webcpp/mongols#3]
Currently I' m working where using aspect in the socket flows control on my java web open source project , could you gives me any flushness points? because my project is very tiny , I can't install NGINX software , so this is why I got only way to integrate the NGINX function in my project . such as limit request , controller filter , proxy etc . may I ask you more important points of NGINX ? 

I' m looking forward to hear your response. thanks.

**Comment by webcpp** [comment]
of course.

**Comment by yaoguangluo** [comment]
Cool sir， now I have already added
1 limit request function
2 cache proxy
3 socket filter
4 concurrent threads limit 
into my tiny project,  it seems very flexible once my project intergrats those useful theories.
could you tell me more Nginx functions especially in the security, encryption, leakage domain? 

Sincerely!

**Comment by webcpp** [comment]
Almost.
You know more than me.
Happy New Year!

**Comment by yaoguangluo** [comment]
OH~~~  Absulitly thanks from the bottom of my really deep heart, any way~
Happy New Year!
