### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [webcpp/mongols#5]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [leveldb_server](https://github.com/webcpp/mongols/blob/3e9f90e7493b1de19af340828da4185c5020ef72/src/leveldb_server.cpp#L14)
- [sqlite_server](https://github.com/webcpp/mongols/blob/3e9f90e7493b1de19af340828da4185c5020ef72/src/sqlite_server.cpp#L11)

**Comment by webcpp** [comment]
It's not necessary.
