### ISSUE TITLE
Add a function to check if the server is still running after signal is catched

### ISSUE THREAD

**Issue by symisc** [webcpp/mongols#7]
Since you already installed a SIGTERM handler in your TCP server, the host application cannot install another signal handler for SIGTERM. The TCP server class should make public a function say for example _is_server_running()_ which return **true** if the underlying is serving request or **false** if a signal is cached and the server will no longer serve request. That way, we can run our cleaning routines without erasing your SIGTERM handler.

**Comment by webcpp** [comment]
If you need run a shutdown function or some cleaning routines , I can add a functional parameter for the `run` method.The functional parameter will be called when the tcp server is stopped.

**Comment by symisc** [comment]
Sounds interesting. Notify us when this is done. Thanks

Symisc Systems, SUARL

-----Original Message-----

**Comment by webcpp** [comment]
`set_shutdown`  method will be called when the tcp server is stopped.

**Comment by symisc** [comment]
Great. We will move on shortly. One last thing, we found out that if you use **_-Ofast -m=arch_** in your Makefile instead of **_-O3,_** the resulting binary is faster in most circumstances.
