### ISSUE TITLE
Whitelist of allowed IP address

### ISSUE THREAD

**Issue by symisc** [webcpp/mongols#8]
What is the best way to **allow only a set of known IP address**  (like the blacklist you implemented) to connect to the server and send request to the mongols handler?

**Comment by webcpp** [comment]
Now you can call `set_enable_whitelist` method and `set_whitelist` method to configure a whitelist of known IP address .

**Comment by symisc** [comment]
Great! Thanks for the fast implementation. Could `set_whitelist()` be called while the server main loop  is running say for example when a new IP is to be added or should we reboot the server when we have to add a new IP?

**Comment by webcpp** [comment]
When a new IP is to be added,the best way is reboot the server.

**Comment by symisc** [comment]
from the implementation, the whitelist is a just a `std::vector` so adding a new entry at runtime is harmless and does not require a reboot, right?

**Comment by webcpp** [comment]
For single-threaded sever, you are right.

**Comment by webcpp** [comment]
And the whitelist is a `std::list`.

**Comment by symisc** [comment]
even for multi-threaded tcp server, it should be safe? because thread worker run after IP validation, right?

**Comment by webcpp** [comment]
I think so.

**Comment by webcpp** [comment]
Now you can safety call `set_whitelist` to add a new entry or call `del_whitelist`  to remove a old entry  at runtime.
